<style type='text/css'>
	body {font-family: sans-serif;}
	#gridContainer {border: 1px solid gray; min-height: 300px; position: relative; width: 800px;}
		#gridContainer table thead tr {background: #596066; color: #fff;}
		#gridContainer table thead tr th {cursor: pointer; padding: 10px; text-align: left; width: 15%;}
		#gridContainer table tbody tr td {border-bottom: 1px solid gray; padding: 10px;}
	
	#gridContainer #gridLoading {background: #5db2ff; display: block; height: 100px; margin-top: -50px; position: absolute; top: 50%; width: 100%; z-index: 1000;}
</style>

<div id='gridContainer'>
	<div class='grid'>
		<?php echo $this->partial('/utilisateur-list/grid.phtml', array('list' => $this->list)); ?>
		
		<?php echo $this->partial('/utilisateur-list/bloc/pagination.phtml', array('pageNumberList' => $this->pageNumberList)); ?>
	</div>
	
	<div id='gridLoading' style='display: none;'></div>
</div>

<?php echo $this->paginationList; ?>

<script type='text/javascript'>
function loadData(pageNumber) {
	jQuery.ajax({
		type: 'post',
		url: '/default/utilisateur-list/load',
		data: {
			PN: pageNumber
		},
		beforeSend: function() {
			jQuery('#gridLoading').show();
		},
		success: function(response) {
			jQuery('#gridLoading').hide();
			
			if (response.valid === true) {
				jQuery('#gridContainer .grid').html(response.html);
			}
		},
		error: function(jqXHR, textStatus, errorThrown) {
			jQuery('#gridLoading').hide();
		}
	});
}
</script>