/default/utilisateur/detail

<style type='text/css'>
	.formrow {overflow: hidden; padding-bottom: 8px; padding-top: 8px; white-space: nowrap;}
		.formrow .div-formlabel {text-align: right; vertical-align: top; width: 170px;}
		.formrow .div-formlabel, .formrow .div-forminput, .formrow .div-formselect {display: inline-block;}
			.formlabel {font-weight: bold; text-align: right;}
			
		.formrow .div-forminput, .formrow .div-formselect {margin-left: 8px; text-align: left; width: 300px;}
			.formrow .div-forminput .forminput, .formrow .div-formselect .formselect {width: 100%;}
			.formrow .div-forminput .div-formerror {display: block;}
</style>

<form method='post' action=''>
	<?php echo $this->form->UTI_NOM->render(); ?>
	<?php echo $this->form->CIV_CODE->render(); ?>
	
	<?php echo $this->form->buttonSave->render(); ?>
</form>